export type TalkLine = {
  speaker: 'reimu' | 'marisa';
  text: string;
  audioFile?: string;
  durationSec: number;
  eye: string;
  mouth: string;
};

export const script: TalkLine[] = [
  {speaker: 'reimu', text: 'ねえ魔理沙！ いきなりだけど\n2026年には私の持ってる', durationSec: 5.50, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'なけなしのビットコインは\n一体いくらになってると思う？', durationSec: 4.44, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'お。いきなり金の亡者全開だな霊夢。\nまあその疑問は誰もが持ってるところだぜ', durationSec: 6.57, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '実は世の中には\nとんでもない予測が飛び交ってるんだ', durationSec: 4.33, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'とんでもない予測？', durationSec: 1.77, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'ある男は言った\n「1ビットコインは1億円になる」と', durationSec: 4.18, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'いい一億円！？ うっひょー！\n賽銭箱がパンクするわ！', durationSec: 4.51, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '落ち着け。別のある著名投資家は\n「いや3750万円だ」と言っている', durationSec: 6.31, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'む…まあそれでも十分大金持ちね', durationSec: 3.24, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'かと思えばウォール街の帝王\nJPMorganはこう言っている', durationSec: 4.26, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '「現実的なラインは2550万円だ」とな', durationSec: 4.09, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'ええっ！？ 1億から2500万って…言ってることが違いすぎない？', durationSec: 5.77, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '差額で神社が何個建つと思ってるのよ！', durationSec: 3.35, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'そうなんだよあまりに数字がバラバラすぎて\n「結局誰を信じればいいんだ！」ってなるよな', durationSec: 6.47, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'もし仮にだぞ？ この中で一番強気な「1億円」と予言した本人が', durationSec: 5.98, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '「あ俺の予想精度実は25％しかないんだわ」', durationSec: 4.43, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'って公言してたらどうする？', durationSec: 2.27, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'はあ？ ナメてんの？\n塩まいて追い返すわよそんな奴', durationSec: 4.91, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'だよな実はこの業界\n「プロが重要視する予想」と', durationSec: 4.10, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '「メディア向けの派手な予想」には\n明確な違いがあるんだ', durationSec: 4.48, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '今回はその「見分け方」を徹底解説するぜ\nこれを見れば霊夢も怪しい数字に踊らされなくなるはずだ', durationSec: 7.81, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'なるほどね私の老後がかかってるんだからしっかり頼むわよ！', durationSec: 4.71, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'それじゃあゆっくりしていってね！！！', durationSec: 2.38, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'まずはウォール街のガチのプロたちが描く「堅実な未来図」から見ていこうか', durationSec: 5.46, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '「堅実」って言葉地味だけど一番好きよ', durationSec: 3.66, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'プロたちの特徴はズバリ「データ」と「モデル」に基づいている点だ', durationSec: 5.03, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '最初に紹介するのは『Bitwise』世界最大の暗号資産インデックスファンド運用会社だぜ', durationSec: 6.95, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'なんか強そうな名前ね', durationSec: 2.23, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '8年間の実績があって4,000以上の機関投資家をクライアントに抱えている', durationSec: 5.93, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'いわば「プロ中のプロ」が信頼する企業だな', durationSec: 3.57, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '彼らの予想は「新しい高値を更新する」つまり過去最高額を超えるというものだ', durationSec: 6.38, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'おー！ やっぱり上がるのね！', durationSec: 2.28, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'ただ彼らは「無条件で上がる」とは言っていない「3つの条件をクリアすれば」という慎重な姿勢なんだ', durationSec: 7.36, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'そして次は『JPMorgan』これは聞いたことあるだろ？', durationSec: 3.87, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'もちろんよ世界最大級の金融機関でしょ？', durationSec: 3.78, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '彼らはビットコインを「デジタル時代の金（ゴールド）」と比較するモデルを使っているんだ', durationSec: 6.26, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '金と同じような価値を持つようになれば「17万ドル（約2550万円）」に到達すると計算している', durationSec: 8.30, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '2550万円かぁ…1億と比べると夢がないけどそれでも凄い額ね', durationSec: 6.35, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'これは単なる勘じゃなくて過去の機関投資家の動きを分析した「ガチ予想」だからな', durationSec: 6.33, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'そして3つ目は『Pantera Capital』創業者のDan Morehead氏は', durationSec: 5.80, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '半減期を分析して2025年8月の予測をほぼ的中させた実績があるんだ', durationSec: 6.69, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '実績がある人の言葉は重みが違うわねでいくらって？', durationSec: 4.37, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '彼らの予想は「23万ドル以上」つまり今の価格から倍増するって見込みだな', durationSec: 6.38, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'まとめるとウォール街のプロたちの予想は「15万ドルから23万ドルの間に収まる」', durationSec: 6.54, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'というのが現実的なラインなんだ', durationSec: 2.74, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '今の1.5倍から2.5倍くらいか…堅実ね', durationSec: 4.47, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'だろ？ でも霊夢不思議に思わないか？', durationSec: 3.23, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'プロがこれくらいの数字を出してるのになんで一部の人は', durationSec: 4.06, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '「75万ドル」とか「25万ドル」とか桁違いの数字を叫んでるんだ？', durationSec: 5.80, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '確かに目立ちたいだけ？それとも何か裏があるの？', durationSec: 4.41, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '鋭いな次の章ではそんなインフルエンサーたちの', durationSec: 3.71, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '「本当の正体」について暴いていくぜ', durationSec: 3.22, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'ここからはインフルエンサーたちの予想だ彼らの描く世界はプロとは全く別物だぜ', durationSec: 6.27, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'まず最も強気なのが『Arthur Hayes（アーサー・ヘイズ）』', durationSec: 4.70, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '彼の予想は「50万ドルから75万ドル」だ！', durationSec: 4.02, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'ななじゅうごまんドルー！？ 円安も相まってまさに夢の数字じゃない！', durationSec: 5.25, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '彼の理屈はこうだ「FRB（アメリカの中央銀行）が金融緩和しまくるから', durationSec: 6.27, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'ドルの価値が下がってビットコインに金がなだれ込む」', durationSec: 3.70, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '筋は通ってる気がするわね信じていいの？', durationSec: 3.41, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'ここで衝撃の事実だ実はHayes本人2024年9月にこう公言してるんだ', durationSec: 6.58, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '「自分の予想精度はわずか25％しかない」ってな', durationSec: 4.44, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'ズコーッ！ 4回に3回外れるんかい！', durationSec: 3.52, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '本人も「予想精度は悪い」と認めてるんだよでもこういう極端な数字はニュースになるから', durationSec: 6.79, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'メディアで大きく取り上げられるんだ', durationSec: 2.54, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '視聴率稼ぎに使われてるわけね…', durationSec: 3.01, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '次は『Tim Draper（ティム・ドレイパー）』「ビットコインは25万ドルになる」と予想している', durationSec: 7.19, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'お今度こそ信じていい？', durationSec: 2.08, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'この人の予想には「歴史」があるんだ', durationSec: 3.08, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '2018年に「2022年までに達成する」と言って外し次は「2023年までだ」と言い直し', durationSec: 7.99, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'それも外れて「2025年」そして今は「2026年までだ」と言っている', durationSec: 6.20, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'ただの「ゴールポストずらし」じゃないのよ！いつかは当たるでしょうけど！', durationSec: 5.01, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '投資の世界では「ブロードキャスト予想」なんて呼ばれるな期間を延ばし続ければいつかは当たるからな', durationSec: 6.99, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'そして最後は『Michael Saylor（マイケル・セイラー）』予想は「14万3000ドルから17万ドル」', durationSec: 7.96, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'あれ？ 数字自体はまともね', durationSec: 2.92, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '数字はなでも彼には巨大な「利益相反」がある', durationSec: 3.93, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '彼の会社『MicroStrategy』はとんでもない量のビットコインを保有してるんだ', durationSec: 5.66, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'つまり価格が上がらないと会社が潰れかねない', durationSec: 3.77, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'あー…つまり「上がってもらわないと困る」から良いことしか言わないってこと？', durationSec: 5.60, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '完全にポジショントークとは言わないが「自分たちの利益と一致した予想」', durationSec: 5.33, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'であることは間違いないな', durationSec: 2.21, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'うーん結局誰も信じられない気がしてきたわプロは堅実すぎて夢がないし', durationSec: 5.94, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'インフルエンサーは適当だし…', durationSec: 2.33, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'そう捨てるもんじゃないぜ重要なのは「役割の違い」を理解することだ', durationSec: 5.14, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '最後の章でこの情報の「賢い使い分け方」を伝授するぜ', durationSec: 4.82, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'ここからが一番重要だぜ「プロの予想」と「インフルエンサーの予想」', durationSec: 5.21, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'どう使い分けるべきか', durationSec: 1.93, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '早く教えてよ！混乱して頭から煙が出そうよ', durationSec: 4.45, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'まず「プロの予想」は『羅針盤』だデータに基づいているし利益相反もほぼない', durationSec: 6.03, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '「市場の冷静な分析結果」だからな長期的な資産形成を目指すならこっちを基準にすべきだ', durationSec: 7.25, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'ふむふむじゃあインフルエンサーは？', durationSec: 2.44, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'インフルエンサーの予想は『希望の灯（ともしび）』あるいは『市場の熱狂度チェッカー』だ', durationSec: 6.46, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '彼らは「こうなったら最高だろ！」っていう願望や市場の期待感を代弁してくれているんだ', durationSec: 6.76, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'なるほど「みんながどれくらい夢を見てるか」を測るバロメーターってことね', durationSec: 5.50, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'その通り例えばサセックス大学の教授は「7万5000ドルから15万ドル」と慎重だ', durationSec: 6.97, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'これは「今は価格が安定しない時期」という冷静な分析だ', durationSec: 4.69, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '一方でHayes氏のような爆上げ予想は「外部要因でバブルが起きるかも」という期待感の表れだ', durationSec: 7.29, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'どっちが正しいかじゃなくて「何のためにその情報を見るか」が大事なのね', durationSec: 5.77, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'そう短期的な利益を狙って波に乗りたいならインフルエンサーの「熱狂」を知る必要がある', durationSec: 6.69, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'でも老後資金とか長期投資を考えるならプロの「羅針盤」を見て冷静になるべきだ', durationSec: 6.26, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '羅針盤だけじゃ退屈だけど希望の灯だけじゃ道に迷って遭難する…', durationSec: 5.81, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'ってことね深いわあ', durationSec: 1.90, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'それじゃあ今日のまとめいくぜ', durationSec: 2.23, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'ウォール街のプロの現実的なラインは「15万ドル～23万ドル」', durationSec: 5.20, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'これが信頼できる羅針盤だ', durationSec: 2.46, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'インフルエンサーの爆上げ予想は「市場の期待感」投資判断の基準にしちゃダメだぜ', durationSec: 6.20, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '自分の目的に合わせてこの2つを使い分けること', durationSec: 4.18, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '2026年私のビットコインがいくらになるか…答えは誰かの予想の中じゃなくて', durationSec: 6.98, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '私の判断力次第ってことね', durationSec: 3.00, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'その通りだ今日の話を思い出せばもう変な数字に惑わされることはないはずだぜ', durationSec: 6.06, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'よーし！ まずは堅実に積み立てつつたまに夢を見てニヤニヤすることにするわ！', durationSec: 6.20, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'それが一番健康的な投資かもなこのチャンネルではこれからも過熱する市場の裏側を', durationSec: 6.48, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '霊夢と一緒に冷静に分析していくぜ', durationSec: 3.20, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: '私の億万長者への道を応援してくれる人はぜひチャンネル登録と高評価をお願いね！', durationSec: 6.97, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'ベルマークも押してくれると私が賽銭箱の前で小躍りするわよ！', durationSec: 5.30, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'コメント欄でみんなの「2026年のビットコイン予想」も', durationSec: 4.75, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '教えてくれると嬉しいぜ', durationSec: 2.10, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: '「1億派」か「堅実派」か書き込んでみてくれよな', durationSec: 4.02, eye: '00', mouth: '00'},
  {speaker: 'reimu', text: 'それでは次回の動画でお会いしましょうご視聴ありがとうございました！', durationSec: 4.78, eye: '00', mouth: '00'},
  {speaker: 'marisa', text: 'それでは次回の動画でお会いしましょうご視聴ありがとうございました！', durationSec: 4.52, eye: '00', mouth: '00'},
];
